export const CORE = 'CORE'
export const BALL_JOINT = 'BALL_JOINT'
export const SEGMENT = 'SEGMENT'
export const NECK = 'NECK'
export const HAND = 'HAND'
export const EYE = 'EYE'
export const IRIS = 'IRIS'
export const MOUTH = 'MOUTH'
